apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-app-deployment
  labels:
    app: sinatra-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sinatra-app
  template:
    metadata:
      labels:
        app: sinatra-app
    spec:
      containers:
      - name: sinatra-app
        image: sinatra-app:v1
        ports:
        - containerPort: 3000
