apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-express-deployment
  labels:
    app: hello-world-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-express
  template:
    metadata:
      labels:
        app: hello-world-express
    spec:
      containers:
      - name: hello-world-express
        image: hello-world-express:v1
        ports:
        - containerPort: 3000
